# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/vga_tutorial_students/zedboard_master.xdc

# Block Designs: bd/ip_design/ip_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design || ORIG_REF_NAME==ip_design} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_processing_system7_0_0/ip_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_processing_system7_0_0 || ORIG_REF_NAME==ip_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_xbar_0/ip_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_xbar_0 || ORIG_REF_NAME==ip_design_xbar_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_ps7_0_axi_periph_0/ip_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==ip_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_rst_ps7_0_100M_0/ip_design_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_rst_ps7_0_100M_0 || ORIG_REF_NAME==ip_design_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_axi_gpio_0_0/ip_design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_axi_gpio_0_0 || ORIG_REF_NAME==ip_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_axi_gpio_1_0/ip_design_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_axi_gpio_1_0 || ORIG_REF_NAME==ip_design_axi_gpio_1_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_led_controller_0_0/ip_design_led_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_led_controller_0_0 || ORIG_REF_NAME==ip_design_led_controller_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_zed_audio_ctrl_0_0/ip_design_zed_audio_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_zed_audio_ctrl_0_0 || ORIG_REF_NAME==ip_design_zed_audio_ctrl_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_axi_timer_0_0/ip_design_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_axi_timer_0_0 || ORIG_REF_NAME==ip_design_axi_timer_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_xlconcat_0_0/ip_design_xlconcat_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_xlconcat_0_0 || ORIG_REF_NAME==ip_design_xlconcat_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_clk_wiz_0_0/ip_design_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_clk_wiz_0_0 || ORIG_REF_NAME==ip_design_clk_wiz_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_vga_controller_0_0_1/ip_design_vga_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_vga_controller_0_0 || ORIG_REF_NAME==ip_design_vga_controller_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_proc_sys_reset_0_0/ip_design_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_proc_sys_reset_0_0 || ORIG_REF_NAME==ip_design_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_Debouncer_0_2/ip_design_Debouncer_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_Debouncer_0_2 || ORIG_REF_NAME==ip_design_Debouncer_0_2} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_LFSR_0_0/ip_design_LFSR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_LFSR_0_0 || ORIG_REF_NAME==ip_design_LFSR_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_bonustimer_0_0/ip_design_bonustimer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_bonustimer_0_0 || ORIG_REF_NAME==ip_design_bonustimer_0_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_auto_pc_0/ip_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_auto_pc_0 || ORIG_REF_NAME==ip_design_auto_pc_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_auto_cc_0/ip_design_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_auto_cc_0 || ORIG_REF_NAME==ip_design_auto_cc_0} -quiet] -quiet

# IP: bd/ip_design/ip/ip_design_auto_cc_1/ip_design_auto_cc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ip_design_auto_cc_1 || ORIG_REF_NAME==ip_design_auto_cc_1} -quiet] -quiet

# XDC: u:/ENSC452/FinalStage/adventures_with_ip/adventures_with_ip.gen/sources_1/bd/ip_design/ip_design_ooc.xdc
