# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: U:/ENSC452/FinalStage/adventures_with_ip/adventures_with_ip.srcs/sources_1/bd/ip_design/ip/ip_design_vga_controller_0_0_1/ip_design_vga_controller_0_0.xci
# IP: The module: 'ip_design_vga_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: u:/ENSC452/FinalStage/adventures_with_ip/adventures_with_ip.gen/sources_1/bd/ip_design/ip/fifo_generator_0/fifo_generator_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: u:/ENSC452/FinalStage/adventures_with_ip/adventures_with_ip.gen/sources_1/bd/ip_design/ip/fifo_generator_0/fifo_generator_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: u:/ENSC452/FinalStage/adventures_with_ip/adventures_with_ip.gen/sources_1/bd/ip_design/ip/fifo_generator_0/fifo_generator_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# IP: U:/ENSC452/FinalStage/adventures_with_ip/adventures_with_ip.srcs/sources_1/bd/ip_design/ip/ip_design_vga_controller_0_0_1/ip_design_vga_controller_0_0.xci
# IP: The module: 'ip_design_vga_controller_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: u:/ENSC452/FinalStage/adventures_with_ip/adventures_with_ip.gen/sources_1/bd/ip_design/ip/fifo_generator_0/fifo_generator_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# XDC: u:/ENSC452/FinalStage/adventures_with_ip/adventures_with_ip.gen/sources_1/bd/ip_design/ip/fifo_generator_0/fifo_generator_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: u:/ENSC452/FinalStage/adventures_with_ip/adventures_with_ip.gen/sources_1/bd/ip_design/ip/fifo_generator_0/fifo_generator_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet
